swagger: "2.0"
info:
  description: Run crypto in Direktiv
  title: crypto
  version: "1.0"
  x-direktiv-meta:
    container: direktiv.azurecr.io/functions/crypto
    maintainer: |-
      [direktiv.io](https://www.direktiv.io) 
    issues: https://github.com/direktiv-apps/crypto/issues
    url: https://github.com/direktiv-apps/crypto  
    categories:
    - unknown
    license: |-
      [Apache-2.0](https://www.apache.org/licenses/LICENSE-2.0)
    long-description: >-
      Run crypto in Direktiv as a function
consumes:
- application/json
produces:
- application/json
schemes:
- http
paths:
  /: 
    delete:
      parameters:
        - name: Direktiv-ActionID
          in: header
          type: string
          description: |
            On cancel Direktiv sends a DELETE request to
            the action with id in the header
      x-direktiv:
        cancel: echo 'cancel {{ .DirektivActionID }}'
      responses:
        200:
    post:
      parameters:
        - name: Direktiv-ActionID
          in: header
          type: string
          default: development
          description: |
            direktiv action id is an UUID. 
            For development it can be set to 'development'
        - name: Direktiv-TempDir
          in: header
          type: string
          default: /tmp
          description: |
            direktiv temp dir is the working directory for that request
            For development it can be set to e.g. '/tmp'
        - name: body
          in: body
          schema:
            type: object
            required: ["symbol"]
            properties:
              symbol:
                type: string
      # direktiv code generation is configured here
      x-direktiv-function: |-
        functions:
        - id: crypto
          image: direktiv.azurecr.io/functions/crypto:1.0
          type: knative-workflow
      x-direktiv-examples:
        # ADD MORE EXAMPLES HERE
        - title: Basic
          content: |-
            - id: crypto
              type: action
              action:
                function: crypto
                input: 
                  commands:
                  - command: Example of running crypto
        - title: Advanced
          content: |-
            - id: crypto
              type: action
              action:
                function: crypto
                input: 
                  files:
                  - name: hello.txt
                    data: Hello World
                    mode: '0755'
                  commands:
                  - command: Example of running crypto
      x-direktiv:
        cmds:
        - action: http
          url: https://api.blockchain.com/v3/exchange/tickers/{{ .Symbol }}
        output: |
          { "crypto": {{ index (index . 0) "result" | toJson }} }
      x-direktiv-errors:
        io.direktiv.command.error: Command execution failed
        io.direktiv.output.error: Template error for output generation of the service
        io.direktiv.ri.error: Can not create information object from request
      responses:
        200:
          description: Value of the crypto
          examples:
            crypto:
              crypto: 
                last_trade_price: 23039.44
                price_24h: 23317.82
                symbol: BTC-USD
                volume_24h: 391.2400001
          schema:
            type: object
        default:
          description: generic error response
          headers:
            Direktiv-ErrorCode:
              type: string
            Direktiv-ErrorMessage:
              type: string
          schema:
            $ref: "#/definitions/error"
definitions:
  direktivFile:
    type: object
    x-go-type:
      type: DirektivFile
      import:
        package: github.com/direktiv/apps/go/pkg/apps 
  error:
    type: object
    required:
      - errorCode
      - errorMessage
    properties:
      errorCode:
        type: string
      errorMessage:
        type: string
