swagger: "2.0"
info:
  description: Description for APPNAME
  title: APPNAME
  version: 1.0.0
consumes:
- application/json
produces:
- application/json
schemes:
- http
paths:
  /:
    post:
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          schema:
            type: object
            required:
              - names
            properties:
              hello:
                type: string
                default: myname
              names: 
                type: array
                items: 
                  type: string
              runit:
                type: array
                items: 
                  type: object
                  properties:
                    what:
                      type: string
                    filejens:
                      $ref: "#/definitions/direktivFile"
      # direktiv code generation is configured here
      x-direktiv:  
        debug: true
        cmds:
        # file handling
        - action: exec
          exec: echo jens
          error: my.small.error
          output: /tmp/kk
        # single commands
          # - action: exec
          #   exec: |-
          #     bash -c 'echo { \\\"hello\\\": \\\"{{ .Hello }}\\\"  > /tmp/kk }; echo DONE!!!'
          #   error: my.small.error
          #   output: /tmp/kk
            # continue: true
          # - action: exec
          #   exec: echo Hello2 {{ .Hello }}
          #   env: ["jens=gerke", "1={{ .Hello }}"]
        # output: |
        #   {
        #     {{ $cmd :=  (index . "cmd0") }}
        #     "myvalue": "{{ index $cmd "result" }}"
        #   }

        # foreach
          # - action: foreach
          #   loop: .Names
          #   exec: '{{ .Item }}'
          #   env: ["jens=gerke", "1={{ .Body.Hello }}"]
        

        # http request
          # - action: http
          #   url: http://www.direktiv.io
          #   method: get
          #   # headers: 
          #   #   - jens: sss
          #   #   - sdd: sddd
          #   # username: hello
          #   # password: world
          #   # insecure: true 
          #   # errorNo200: true
          #   # continue: true
          # - action: http
          #   url: http://www.direktiv.io
          #   method: get
          #   headers: 
          #     - jens: sss
          #     - sdd: sddd
          #   username: hello
          #   password: world
          #   insecure: true 
          #   errorNo200: false
          # - action: foreachHttp
          #   url: http://www.direktiv.io
          #   loop: .Names
          #   method: get

      responses:
        200:
          description: list the todo operations
          schema:
            type: object
            additionalProperties: {}
        
          # schema:
          #   type: object
          #   properties: 
          #     myvalue: 
          #       type: string
        default:
          description: generic error response
          headers:
            Direktiv-ErrorCode:
              type: string
            Direktiv-ErrorMessage:
              type: string
          schema:
            $ref: "#/definitions/error"
definitions:
  direktivFile:
    type: object
    x-go-type:
      type: DirektivFile
      import:
        package: github.com/direktiv/apps/go/pkg/apps 
  error:
    type: object
    required:
      - errorCode
      - errorMessage
    properties:
      errorCode:
        type: string
      errorMessage:
        type: string
